import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Convex App',
  description: 'Generated by create app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
