/**
 * Deployment guide generator
 *
 * Generates docs/deployment.md adapted to the selected backend, database,
 * and project structure options.
 */

import type { ProjectConfig } from '../../types/schemas'

/** Human-readable backend name for docs */
function backendLabel(backend: ProjectConfig['backend']): string {
  switch (backend) {
    case 'express-bun':
      return 'Express (Bun)'
    case 'hono-bun':
      return 'Hono (Bun)'
    case 'fastify-node':
      return 'Fastify (Node.js)'
    case 'go-fiber':
      return 'Go Fiber'
    case 'rust-axum':
    case 'rust-actix':
      return 'Rust Axum'
    case 'python-fastapi':
      return 'Python FastAPI'
    case 'none':
      return 'None (frontend only)'
  }
}

/** Host recommendations per backend */
function hostingHint(backend: ProjectConfig['backend']): string {
  switch (backend) {
    case 'express-bun':
    case 'hono-bun':
      return 'Railway, Fly.io, Render, or another Bun-friendly host'
    case 'fastify-node':
      return 'Railway, Fly.io, Render, or any Node.js host'
    case 'go-fiber':
      return 'Railway, Fly.io, Google Cloud Run, or any container host'
    case 'rust-axum':
    case 'rust-actix':
      return 'Railway, Fly.io, or any container host'
    case 'python-fastapi':
      return 'Railway, Fly.io, Render, or any Python host'
    case 'none':
      return 'N/A (frontend only)'
  }
}

export function renderDeploymentGuide(config: ProjectConfig): string {
  const workerLine = config.includeWorker
    ? '- Deploy `apps/worker` as a separate Railway or container service if background jobs are required.'
    : '- Worker deployment is not needed unless you add the workspace back later.'

  const dockerLine = config.includeDocker
    ? `- Local Docker services are available via \`docker-compose.yml\` for ${config.database === 'postgres' ? 'PostgreSQL and ' : config.database === 'mongodb' ? 'MongoDB and ' : ''}Redis.`
    : `- Local Docker services were not generated; provide managed database and Redis endpoints manually.`

  const serverEnvVars =
    config.backend !== 'none'
      ? `- Server:
  \`PORT\`, \`NODE_ENV\`, ${config.database !== 'none' ? '`DATABASE_URL`, ' : ''}\`REDIS_URL\`, \`FRONTEND_URL\`,
  \`BETTER_AUTH_URL\`, \`BETTER_AUTH_SECRET\``
      : ''

  return `# Deployment Guide

## Stack

- Backend: ${backendLabel(config.backend)}
- Database: ${config.database}
- ORM: ${config.orm}

## Recommended Split

- Deploy \`apps/web\` to Vercel.
${config.backend !== 'none' ? `- Deploy \`apps/server\` to ${hostingHint(config.backend)}.` : '- No backend server to deploy.'}
${workerLine}

## Required Environment Variables

- Web:
  \`NEXT_PUBLIC_APP_URL\`, \`NEXT_PUBLIC_API_URL\`
${serverEnvVars}

## Local Services

${dockerLine}

## Suggested Rollout Order

1. ${config.database !== 'none' ? 'Deploy the database and Redis.' : 'Deploy Redis (or skip if not needed).'}
2. ${config.backend !== 'none' ? 'Deploy the server and validate `/health`.' : 'Skip (no backend).'}
3. Deploy the web app with the correct \`NEXT_PUBLIC_API_URL\`.
4. Add CI gates before the first production release.

## Deploy API to Render

**Recommended:** Dashboard → **New Blueprint Instance** → repo root \`render.yaml\`.

The blueprint creates Docker web service \`arche-template-api\`, Postgres, and internal Key Value (Redis). Do **not** use Native Bun with \`bun run apps/server/dist/server.js\` from repo root — Render’s default Bun 1.1 lacks APIs this template used to rely on.

| Setting | Value |
|---------|--------|
| Runtime | **Docker** (from blueprint) |
| Dockerfile | \`apps/server/Dockerfile\` (context = repo root) |
| Health check | \`/health\` |
| Welcome | \`GET /\` returns JSON index |

After first deploy, set \`FRONTEND_URL\` (Vercel) and \`BETTER_AUTH_URL\` (this service’s public HTTPS URL).

Full guide (failure causes, checklist, Vercel env): \`docs/deployment-render.md\` in the template repo.

**Common failure causes:**

1. **Native Bun 1.1** — use Docker blueprint or pin \`.bun-version\`; app Redis uses ioredis.
2. **Missing Redis** — blueprint wires \`REDIS_URL\`; manual deploys must set it.
3. **Wrong URLs** — \`BETTER_AUTH_URL\` and \`FRONTEND_URL\` must be production HTTPS, not localhost.
4. **CORS** — \`FRONTEND_URL\` must match the browser origin exactly.

After deploy: \`curl https://<your-service>.onrender.com/\` and \`curl .../health\`

## Notes

This guide was generated by \`@arche/create\` for ${config.projectName}.
Review it alongside the repo docs before production rollout.
`
}
