/**
 * Deployment guide generator
 *
 * Generates docs/deployment.md adapted to the selected backend, database,
 * and project structure options.
 */

import type { ProjectConfig } from '../../types/schemas'

/** Human-readable backend name for docs */
function backendLabel(backend: ProjectConfig['backend']): string {
  switch (backend) {
    case 'express-bun':
      return 'Express (Bun)'
    case 'hono-bun':
      return 'Hono (Bun)'
    case 'fastify-node':
      return 'Fastify (Node.js)'
    case 'go-fiber':
      return 'Go Fiber'
    case 'rust-axum':
    case 'rust-actix':
      return 'Rust Axum'
    case 'python-fastapi':
      return 'Python FastAPI'
    case 'none':
      return 'None (frontend only)'
  }
}

export function renderDeploymentGuide(config: ProjectConfig): string {
  const workerLine = config.includeWorker
    ? '- **Path B:** deploy `apps/worker` on Render (or similar) with `REDIS_URL`.'
    : '- Worker optional unless you enable background jobs.'

  const dockerLine = config.includeDocker
    ? `- Local: \`docker compose\` for ${config.database === 'postgres' ? 'Postgres and ' : config.database === 'mongodb' ? 'MongoDB and ' : ''}Redis.`
    : `- Provide managed Postgres and Redis URLs in production.`

  const serverBlock =
    config.backend === 'express-bun' || config.backend === 'hono-bun'
      ? `
## Path A — Vercel (web + API)

- Deploy \`apps/web\` and \`apps/server\` as **two Vercel projects**.
- Server entry: \`apps/server/src/vercel-handler.ts\`; build: \`bun run build:vercel --filter=@template/server\`.
- Set \`DATABASE_URL\`, \`BETTER_AUTH_*\`, \`FRONTEND_URL\`, \`REDIS_URL\` on the **server** project (Neon, Upstash, etc.).
- Web: \`NEXT_PUBLIC_API_URL\` → server project URL.

See template repo \`docs/deployment-vercel.md\` for full steps.

## Path B — Vercel web + Render API

- Deploy \`apps/web\` on Vercel; \`apps/server\` on Render Docker.
- **B1:** Blueprint from repo \`render.yaml\` (Postgres + Redis wired).
- **B2:** \`render.api-only.yaml\` + external \`DATABASE_URL\` / \`REDIS_URL\`.
- Do **not** use \`bun run apps/server/dist/server.js\` from repo root on Render.

See template repo \`docs/deployment-render.md\` for troubleshooting.

${workerLine}
`
      : config.backend !== 'none'
        ? `
## Backend hosting

Deploy \`apps/server\` to a container-friendly host (Railway, Fly.io, Render). Env matrix: same names as \`docs/deployment-env.md\` in the template repo.
`
        : ''

  return `# Deployment Guide

Generated for **${config.projectName}** (${backendLabel(config.backend)}, ${config.database}, ${config.orm}).

Production env matrix: copy from template [deployment-env.md](https://github.com/KitsuneKode/template-nextjs-express-trpc-better-auth-monorepo/blob/main/docs/deployment-env.md) or maintain \`docs/deployment-env.md\` in this repo.

## Stack

- Backend: ${backendLabel(config.backend)}
- Database: ${config.database}
- ORM: ${config.orm}

## Rollout order

1. Provision Postgres${config.database !== 'none' ? '' : ' (if applicable)'} and Redis (or \`ENABLE_REDIS=false\`).
2. Deploy API; run migrations; verify \`/health\`.
3. Deploy web with \`NEXT_PUBLIC_API_URL\` pointing at the API.
${serverBlock}
## Required environment variables

Use one matrix for all targets — see template \`docs/deployment-env.md\`:

- **Web (Vercel):** \`NEXT_PUBLIC_APP_URL\`, \`NEXT_PUBLIC_API_URL\`
- **API:** \`DATABASE_URL\`, \`BETTER_AUTH_SECRET\`, \`BETTER_AUTH_URL\`, \`FRONTEND_URL\`, \`REDIS_URL\` or \`ENABLE_REDIS=false\`

## Local services

${dockerLine}

## Notes

This guide was generated by \`@arche/create\`. For the full two-path hub, see the template [docs/deployment.md](https://github.com/KitsuneKode/template-nextjs-express-trpc-better-auth-monorepo/blob/main/docs/deployment.md).
`
}
