import type { ProjectConfig } from '../../types/schemas'

/** Root .gitignore for scaffolded projects (merged with template copy when present). */
export function renderGitignore(config: ProjectConfig): string {
  const blocks = [
    `# Generated by @arche/create — safe to edit`,
    ``,
    `# Dependencies`,
    `node_modules/`,
    `.pnp`,
    `.pnp.js`,
    ``,
    `# Environment`,
    `.env`,
    `.env.local`,
    `.env.*.local`,
    `!.env.example`,
    ``,
    `# Build / cache`,
    `.next/`,
    `out/`,
    `build/`,
    `dist/`,
    `.turbo/`,
    `.vercel/`,
    `.source/`,
    ``,
    `# Logs`,
    `logs/`,
    `*.log`,
    ``,
    `# Testing`,
    `coverage/`,
    ``,
    `# OS / IDE`,
    `.DS_Store`,
    `*.pem`,
    `.claude/settings.local.json`,
    `.context/`,
  ]

  if (
    config.family === 'rust' ||
    config.backend === 'rust-axum' ||
    config.backend === 'rust-actix'
  ) {
    blocks.push(``, `# Rust`, `target/`, `**/*.rs.bk`)
  }

  if (config.backend === 'go-fiber' || config.family === 'polyglot') {
    blocks.push(``, `# Go`, `bin/`, `vendor/`)
  }

  if (config.backend === 'python-fastapi') {
    blocks.push(``, `# Python`, `__pycache__/`, `*.py[cod]`, `.venv/`, `venv/`)
  }

  if (config.family === 'solana') {
    blocks.push(``, `# Solana / Anchor`, `target/`, `.anchor/`)
  }

  return blocks.join('\n') + '\n'
}
