/**
 * SHOWCASE.mdx generator
 *
 * Generates a portfolio-ready SHOWCASE.mdx file at the project root.
 * The portfolio at kitsunekode.in picks this up via GitHub webhook.
 */

import type { ProjectConfig } from '../../types/schemas'
import { sanitizeProjectName } from '../scaffold'

export function buildShowcaseMdx(config: ProjectConfig): string {
  const name = sanitizeProjectName(config.projectName)

  return `---
title: ${name}
type: fullstack
tags: [${config.backend}, ${config.database}, ${config.orm}]
featured: false
created: ${new Date().toISOString().split('T')[0]}
---

# ${name}

## Why I Built This

<!-- Tell the story — what problem does this solve, why does it exist? -->

## Architecture

<!-- Describe the architecture, key decisions, and trade-offs. -->

## Key Features

<!-- List the standout features. -->

## Getting Started

\`\`\`bash
bun install
bun dev
\`\`\`

---

*This SHOWCASE.mdx was auto-generated by @kitsu/create. Fill it in and push to make your project appear on the portfolio.*
`
}
